2018-12-02 18:02:15 DEBUG db_query [db.py-16] select * from user where name='张三'
2018-12-02 18:02:15 DEBUG db_query [db.py-21] ((9188, '张三', 'e10adc3949ba59abbe56e057f20f883e'),)
2018-12-02 18:02:15 DEBUG _new_conn [connectionpool.py-208] Starting new HTTP connection (1): 115.28.108.130
2018-12-02 18:02:15 DEBUG _make_request [connectionpool.py-396] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
2018-12-02 18:02:15 INFO log_case_info [case_log.py-4] --------------------------------------------------
2018-12-02 18:02:15 INFO log_case_info [case_log.py-5] 执行用例: test_user_login_normal
2018-12-02 18:02:15 INFO log_case_info [case_log.py-6] 接口地址: http://115.28.108.130:5000/api/user/login/
2018-12-02 18:02:15 INFO log_case_info [case_log.py-7] 请求数据:  {"name": "张三", "password": "123456"}
2018-12-02 18:02:15 INFO log_case_info [case_log.py-8] 期望结果: <h1>登录成功</h1>
2018-12-02 18:02:15 INFO log_case_info [case_log.py-9] 实际结果: <h1>登录成功</h1>
2018-12-02 18:07:20 DEBUG _new_conn [connectionpool.py-208] Starting new HTTP connection (1): 115.28.108.130
2018-12-02 18:07:20 DEBUG _make_request [connectionpool.py-396] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 152
2018-12-02 18:07:20 INFO log_case_info [case_log.py-4] --------------------------------------------------
2018-12-02 18:07:20 INFO log_case_info [case_log.py-5] 执行用例: test_user_reg_use_exist
2018-12-02 18:07:20 INFO log_case_info [case_log.py-6] 接口地址: http://115.28.108.130:5000/api/user/reg/
2018-12-02 18:07:20 INFO log_case_info [case_log.py-7] 请求数据:  {"name": "张三", "password": "123456"}
2018-12-02 18:07:20 INFO log_case_info [case_log.py-8] 期望结果: {
    "code": "100001",
    "data": {
        "name": "张三",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "失败，用户已存在"
}
2018-12-02 18:07:20 INFO log_case_info [case_log.py-9] 实际结果: {"code":"100001","data":{"name":"\u5f20\u4e09","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u5931\u8d25\uff0c\u7528\u6237\u5df2\u5b58\u5728"}

2018-12-02 18:07:27 DEBUG db_query [db.py-16] select * from user where name='张三丰'
2018-12-02 18:07:27 DEBUG db_query [db.py-21] ()
2018-12-02 18:07:27 DEBUG _new_conn [connectionpool.py-208] Starting new HTTP connection (1): 115.28.108.130
2018-12-02 18:07:27 DEBUG _make_request [connectionpool.py-396] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 122
2018-12-02 18:07:27 INFO log_case_info [case_log.py-4] --------------------------------------------------
2018-12-02 18:07:27 INFO log_case_info [case_log.py-5] 执行用例: test_user_reg_normal
2018-12-02 18:07:27 INFO log_case_info [case_log.py-6] 接口地址: http://115.28.108.130:5000/api/user/reg/
2018-12-02 18:07:27 INFO log_case_info [case_log.py-7] 请求数据:  {"name": "张三丰", "password": "123456"}
2018-12-02 18:07:27 INFO log_case_info [case_log.py-8] 期望结果: {
    "code": "100000",
    "data": {
        "name": "张三丰",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "成功"
}
2018-12-02 18:07:27 INFO log_case_info [case_log.py-9] 实际结果: {"code":"100000","data":{"name":"\u5f20\u4e09\u4e30","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u6210\u529f"}

2018-12-02 18:07:27 DEBUG db_change [db.py-28] delete from user where name = '张三丰'
2018-12-02 18:07:28 DEBUG _new_conn [connectionpool.py-208] Starting new HTTP connection (1): 115.28.108.130
2018-12-02 18:07:28 DEBUG _make_request [connectionpool.py-396] http://115.28.108.130:5000 "POST /api/user/reg/ HTTP/1.1" 200 152
2018-12-02 18:07:28 INFO log_case_info [case_log.py-4] --------------------------------------------------
2018-12-02 18:07:28 INFO log_case_info [case_log.py-5] 执行用例: test_user_reg_use_exist
2018-12-02 18:07:28 INFO log_case_info [case_log.py-6] 接口地址: http://115.28.108.130:5000/api/user/reg/
2018-12-02 18:07:28 INFO log_case_info [case_log.py-7] 请求数据:  {"name": "张三", "password": "123456"}
2018-12-02 18:07:28 INFO log_case_info [case_log.py-8] 期望结果: {
    "code": "100001",
    "data": {
        "name": "张三",
        "password": "e10adc3949ba59abbe56e057f20f883e"
    },
    "msg": "失败，用户已存在"
}
2018-12-02 18:07:28 INFO log_case_info [case_log.py-9] 实际结果: {"code":"100001","data":{"name":"\u5f20\u4e09","password":"e10adc3949ba59abbe56e057f20f883e"},"msg":"\u5931\u8d25\uff0c\u7528\u6237\u5df2\u5b58\u5728"}

